#!/usr/bin/env bash

main() {
  local wd=$HOME/h_
  local s=home
  cd $wd
  
  tmux new-session -d -s $s -n "main"
  #---------------------------------------------------------------------------
  tmux select-window -t $s:1
  tmux attach -t $s:1 
}

main
