#!/usr/bin/env bash

main() {
  local wd=$HOME/spaces/work/embed/pages-next
  local s=pages-next
  cd $wd
  
  tmux new-session -d -s $s -n "main"
  tmux new-window -t $s:1 -n "logs"
  tmux select-window -t $s:1
  tmux attach -t $s:1 
}

main
