#!/usr/bin/env bash

set -e

vi() {
  vim "$@"
}

main() {
  local a="$1"
  if [ "$a" = "new" ]; then
    vi $chk_dotfiles_path/mux-bin/mux-example;
  elif [ "$a" = "new2" ]; then
    vi $chk_dotfiles_path/mux-bin/mux-example2;
  elif [ -z "$a" ]; then
    vi $chk_dotfiles_path/mux-bin/mux-example;
  else
    mux-$a
  fi
}

main $@
