#!/usr/bin/env bash

main() {
  local wd=$HOME/sandbox/damp-star
  local s=damp-star
  cd $wd
  
  tmux new-session -d -s $s -n "main"
  tmux send-keys -t $s:1 "ssh damp-star" C-m
  #---------------------------------------------------------------------------
  tmux select-window -t $s:1
  tmux attach -t $s:1 
}

main
