#!/usr/bin/env bash

main() {
  local wd=$HOME/pid/code-server
  local s=code-server
  cd $wd
  
  tmux new-session -d -s $s -n "main"
  tmux new-window -t $s:2 -n "code-server"
  tmux send-keys -t $s:2 "code-server" C-m
  tmux select-window -t $s:1
  #tmux attach -t $s:1 
}

main
