#!/usr/bin/env bash

main() {
  local wd=$HOME/desktop
  local s=chrome
  cd $wd
  
  local x=$(tmux-session-exists $s)
  if [[ "$x" = "true" ]]; then
    exit 0
  fi

  tmux new-session -d -s $s -n "main"
  tmux send-keys -t $s:1 "google-chrome" C-m
}

main

