#!/usr/bin/env bash

main() {
  local wd=$HOME/sandbox
  local s=sandbox
  cd $wd
  
  tmux new-session -d -s $s -n "main"
  #---------------------------------------------------------------------------
  tmux select-window -t $s:1
  tmux attach -t $s:1 
}

main
