#!/usr/bin/env bash

main() {
  local wd=$HOME/dev/sslcom-rails
  local s=sslcom
  cd $wd
  
  tmux new-session -d -s $s -n "main"
  #---------------------------------------------------------------------------
  tmux new-window -t $s:2 -n "server"
  tmux send-keys -t $s:2 "bundle exec puma -b 'ssl://0.0.0.0:3000?key=config/cert/key.pem&cert=config/cert/cert.pem' --environment=development" C-m
  tmux split-window -t $s:2 -h
  tmux send-keys -t $s:2 "tail -f log/development.log" C-m
  #---------------------------------------------------------------------------
  tmux new-window -t $s:3 -n "console"
  tmux send-keys -t $s:3 "rails c" C-m
  #---------------------------------------------------------------------------
  tmux new-window -t $s:4 -n "services"
  tmux send-keys -t $s:4 "redis-server" C-m
  tmux split-window -t $s:4 -v
  tmux send-keys -t $s:4 "mailcatcher -f" C-m
  #---------------------------------------------------------------------------
  tmux select-window -t $s:1
  tmux attach -t $s:1 
}

main

