#!/usr/bin/env bash

main() {
  local wd=$HOME/dev/cmediaplayer_web
  local s=react-ui
  cd $wd
  
  tmux new-session -d -s $s -n "main"
  tmux send-keys -t $s:1 "vi README.md" C-m
  #---------------------------------------------------------------------------
  tmux new-window -t $s:2 -n "server"
  tmux send-keys -t $s:2 "npm run dev" C-m
  #---------------------------------------------------------------------------
  tmux select-window -t $s:1
  tmux attach -t $s:1 
}

main
