#!/usr/bin/env bash

main() {
  local wd=$HOME/desktop
  local s=desktop
  cd $wd
  
  tmux new-session -d -s $s -n "main"
  tmux send-keys -t $s:1 "postgres-start" C-m
  #---------------------------------------------------------------------------
  tmux new-window -t $s:2 -n "puma-dev"
  tmux send-keys -t $s:2 "puma-dev-run" C-m
  #---------------------------------------------------------------------------
  tmux new-window -t $s:3 -n "redis"
  tmux send-keys -t $s:3 "redis-server" C-m
  #---------------------------------------------------------------------------
  tmux new-window -t $s:4 -n "mailcatcher"
  tmux send-keys -t $s:4 "mailcatcher -f" C-m
  #---------------------------------------------------------------------------
  tmux select-window -t $s:1
  tmux attach -t $s:1 
}

main

