#!/usr/bin/env bash

main() {
  local wd=$HOME/desktop
  local s=desktop
  cd $wd

  local x=$(tmux-session-exists $s)
  if [[ "$x" = "true" ]]; then
    exit 0
  fi
  
  tmux new-session -d -s $s -n "main"
  tmux send-keys -t $s:1 "postgres-start" C-m
  #---------------------------------------------------------------------------
  tmux new-window -t $s:2 -n "puma-dev"
  tmux send-keys -t $s:2 "puma-dev-run" C-m
  #---------------------------------------------------------------------------
  tmux new-window -t $s:3 -n "redis"
  tmux send-keys -t $s:3 "redis-server" C-m
  #---------------------------------------------------------------------------
  tmux new-window -t $s:4 -n "mailcatcher"
  tmux send-keys -t $s:4 "mailcatcher -f" C-m
}

main
